version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  flask-app:
    build: ./
    container_name: flask-app
    ports:
      - "9647:9647"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mongo

    depends_on:
      - mongodb

