version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Port für die MongoDB

  flask-app:
    build: ./ # Verweis auf das Verzeichnis mit Ihrer Flask-Anwendung
    container_name: flask-app
    ports:
      - "9647:9647"  # Port für Ihre Flask-Anwendung
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mongo  # Verbindungs-URI zur MongoDB

    depends_on:
      - mongodb  # Flask-App wartet auf die Verfügbarkeit der MongoDB

